name: fritz_tools
description: "Fritz!Box tools — device list, mesh management & diagnostics"
publish_to: 'none'
version: 1.3.0+11

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.12.0
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  http: ^1.3.0
  crypto: ^3.0.6
  cupertino_icons: ^1.0.8
  network_info_plus: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
